/**
 * POST /api/paragon/calculate
 * BTD6 Paragon degree calculator — designed for Discord bots and external integrations.
 *
 * ── Required body field ───────────────────────────────────────────────────────
 *   tower          {string}  Tower name, paragon name, or paragon ID
 *                            e.g. "Dart Monkey", "Apex Plasma Master", "apex_plasma_master"
 *
 * ── Optional body fields (all default to 0 / "medium" / 1) ───────────────────
 *   pops           {number}  Total pops across all sacrificed towers       (default: 0)
 *   cash_spent     {number}  Cash spent on non-T5 towers before sacrifice  (default: 0)
 *   tier5_count    {number}  Extra T5s sacrificed BEYOND the 3 required    (default: 0, integer)
 *   upgrade_count  {number}  Total upgrade tiers on sacrificed non-T5s     (default: 0, integer)
 *   geraldo_totems {number}  Geraldo Paragon Power Totems absorbed          (default: 0, integer)
 *   player_count   {number}  1 = solo, 2–4 = co-op                         (default: 1, integer 1–4)
 *   difficulty     {string}  "easy"|"medium"|"hard"|"impoppable"            (default: "medium")
 *   income         {number}  Cash income generated by sacrificed towers     (default: 0)
 *   slider_cash    {number}  Cash injected via the in-game cash slider      (default: 0)
 *
 * ── Auth (optional) ───────────────────────────────────────────────────────────
 *   Send X-API-Key header.  Set PARAGON_API_KEYS env var (comma-separated list)
 *   to enable.  Valid key holders get 300 req/min instead of 60 req/min.
 *   Leave PARAGON_API_KEYS unset to run without key enforcement.
 *
 * ── Rate limit headers ────────────────────────────────────────────────────────
 *   X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset
 *   Retry-After (on 429 responses only)
 *
 * ── Request / Response tracing ───────────────────────────────────────────────
 *   X-Request-ID is echoed on every response (generated if not supplied by client).
 *
 * ── Note on rate-limit reliability ───────────────────────────────────────────
 *   This endpoint is a Vercel serverless function; each cold-start instance has
 *   its own in-memory counter.  Counts are best-effort.  Use the response headers
 *   to self-throttle on the client side.
 */

import { randomUUID } from "node:crypto";
import {
  API_VERSION, FORMULA_VERSION, FORMULA_REVISION,
  VALID_DIFFICULTIES, PARAGONS, POWER_LIMITS,
  calculateParagonData,
} from "../_lib/shared.js";

// ─── Calculator ──────────────────────────────────────────────────────────────
//
// The degree maths lives in src/utils/calculator.js and is shared with the web
// app, so the API and the site can never disagree about the same build. This
// layer only reshapes the engine's result into the documented JSON contract.

function runCalculation({
  paragon, difficulty, gameMode,
  pops, income, upgrades, extraT5s,
  sacrificedTowerCash, sliderCash, totems,
}) {
  const calc = calculateParagonData({
    paragon, difficulty, gameMode,
    pops, income, upgrades, extraT5s,
    sacrificedTowerCash, sliderCash, totems,
  });

  const basePrice           = calc.basePrice;
  const sacrificePowerRatio = 20000 / basePrice;
  const sliderPowerRatio    = 20000 / (basePrice * 1.05);
  const bd                  = calc.powerBreakdown;

  const warnings = [];

  if (calc.ignoredExtraT5s > 0 && gameMode === "solo") {
    warnings.push({
      type: "invalid_extra_t5s_solo",
      message:
        "In solo play, only Dart Monkey can sacrifice an extra T5 (via Master Double Cross). " +
        "Extra T5s were ignored for this calculation.",
    });
  }
  if (calc.ignoredExtraT5s > 0 && gameMode === "coop") {
    warnings.push({
      type: "invalid_extra_t5s_coop",
      message:
        "Co-op allows at most 9 extra T5s (four players with three T5s each, minus the three " +
        "the Paragon consumes). The surplus was ignored for this calculation.",
    });
  }
  if (bd.t5.capped) {
    // 9 extra T5s are worth 54,000 raw power against a 50,000 cap, so the
    // overflow is reported as power rather than as a whole number of towers.
    const wastedPower =
      Math.min(extraT5s, 9) * POWER_LIMITS.t5.pointsPerExtra - POWER_LIMITS.t5.maxPower;
    warnings.push({
      type: "extra_t5s_capped",
      message: `Extra-T5 power is capped at 50,000. ${wastedPower.toLocaleString()} power from extra T5s is wasted.`,
    });
  }
  if (bd.upgrades.capped) {
    warnings.push({
      type: "upgrades_capped",
      message: `Upgrade power is capped at 10,000. ${upgrades - 100} upgrade tier(s) are wasted.`,
    });
  }
  if (bd.pops.capped) {
    const wastedPops = Math.round(pops + income * 4 - 16200000);
    warnings.push({
      type: "pops_capped",
      message: `Pops/income power is capped at 90,000. ${wastedPops.toLocaleString()} equivalent pop(s) are wasted.`,
    });
  }
  if (bd.cash.capped && calc.wastedCash > 0) {
    warnings.push({
      type: "cash_capped",
      message: `Cash power is capped at 60,000. $${calc.wastedCash.toLocaleString()} is wasted — reduce cash sacrifice or slider input.`,
    });
  }

  return {
    basePrice,
    totalPower:   calc.totalPower,
    degree:       calc.degree,
    nextDegree:   calc.nextDegree,
    powerForNext: calc.powerGap,
    breakdown: {
      pops: {
        power:     bd.pops.power,
        max_power: bd.pops.max,
        capped:    bd.pops.capped,
        fill_pct:  round2(bd.pops.pct),
        note:      "1 power per 180 pops (equivalent: $45 income = 180 pops)",
      },
      upgrades: {
        power:     bd.upgrades.power,
        max_power: bd.upgrades.max,
        capped:    bd.upgrades.capped,
        fill_pct:  round2(bd.upgrades.pct),
        note:      "100 power per upgrade tier on sacrificed non-T5 towers (max 100 tiers = 10,000 power)",
      },
      cash: {
        power:     bd.cash.power,
        max_power: bd.cash.max,
        capped:    bd.cash.capped,
        fill_pct:  round2(bd.cash.pct),
        note:      `Power rate: ${round2(sacrificePowerRatio)} per $1 (sacrifice) / ${round2(sliderPowerRatio)} per $1 (slider, 5% premium)`,
      },
      extra_t5s: {
        power:     bd.t5.power,
        max_power: bd.t5.max,
        capped:    bd.t5.capped,
        fill_pct:  round2(bd.t5.pct),
        note:      "6,000 power per extra T5 beyond the 3 required to build the paragon (max ~8 extras = 50,000 power)",
      },
      totems: {
        power:     bd.totems.power,
        max_power: null,
        capped:    false,
        fill_pct:  null,
        note:      "2,000 power per Geraldo Paragon Power Totem (uncapped)",
      },
    },
    warnings,
    wastedCash: calc.wastedCash,
  };
}

function round2(n) {
  return Math.round(n * 100) / 100;
}

// ─── Tower lookup ─────────────────────────────────────────────────────────────

function findParagon(input) {
  if (!input) return null;
  const q = String(input).trim().toLowerCase();
  return Object.values(PARAGONS).find(
    (p) =>
      p.id.toLowerCase() === q ||
      p.tower.toLowerCase() === q ||
      p.name.toLowerCase() === q
  ) ?? null;
}

// ─── Rate limiter (per-instance in-memory, best-effort) ──────────────────────

const rateMap = new Map();
const WINDOW_MS = 60_000;

function checkRate(ip, limit) {
  const now = Date.now();
  let entry = rateMap.get(ip);
  if (!entry || now >= entry.resetAt) {
    entry = { count: 0, resetAt: now + WINDOW_MS };
    rateMap.set(ip, entry);
  }
  entry.count++;
  return {
    allowed:   entry.count <= limit,
    remaining: Math.max(0, limit - entry.count),
    resetIn:   Math.ceil((entry.resetAt - now) / 1000),
    limit,
  };
}

const pruneTimer = setInterval(() => {
  const now = Date.now();
  for (const [k, v] of rateMap) {
    if (now >= v.resetAt) rateMap.delete(k);
  }
}, 5 * 60_000);
pruneTimer.unref?.();

// Exposed only for unit tests — not part of the public API surface.
export function _resetRateLimitForTesting() {
  rateMap.clear();
}

// ─── Input validation ─────────────────────────────────────────────────────────

const MAX_INPUT = 1e15; // guard against overflow abuse

/**
 * Validates a numeric field from the request body.
 * Returns { error, value } where error is null on success.
 * If val is absent/empty, returns the defaultValue without error.
 */
function validateNumericField(val, name, opts = {}) {
  const { integer = false, min = 0, max = MAX_INPUT, defaultValue = 0 } = opts;

  if (val === undefined || val === null || val === "") {
    return { error: null, value: defaultValue };
  }

  const n = Number(val);

  if (Number.isNaN(n)) {
    return {
      error: { code: "INVALID_FIELD", message: `'${name}' must be a number.`, field: name },
      value: null,
    };
  }
  if (!Number.isFinite(n)) {
    return {
      error: { code: "INVALID_FIELD", message: `'${name}' must be a finite number (not Infinity).`, field: name },
      value: null,
    };
  }
  if (n < min) {
    return {
      error: { code: "INVALID_FIELD", message: `'${name}' must be >= ${min}, got ${n}.`, field: name },
      value: null,
    };
  }
  if (n > max) {
    return {
      error: { code: "INVALID_FIELD", message: `'${name}' must be <= ${max}, got ${n}.`, field: name },
      value: null,
    };
  }
  if (integer && !Number.isInteger(n)) {
    return {
      error: { code: "INVALID_FIELD", message: `'${name}' must be a whole number (no decimals), got ${n}.`, field: name },
      value: null,
    };
  }

  return { error: null, value: n };
}

function validateDifficultyField(val) {
  if (val === undefined || val === null || val === "") {
    return { error: null, value: "medium" };
  }
  const v = String(val).toLowerCase().trim();
  if (!VALID_DIFFICULTIES.includes(v)) {
    return {
      error: {
        code:               "INVALID_FIELD",
        message:            `'difficulty' must be one of: ${VALID_DIFFICULTIES.join(", ")}. Got "${val}".`,
        field:              "difficulty",
        valid_difficulties: VALID_DIFFICULTIES,
      },
      value: null,
    };
  }
  return { error: null, value: v };
}

// ─── Handler ──────────────────────────────────────────────────────────────────

export default function handler(req, res) {
  // Echo or generate a request-scoped tracing ID.
  const requestId = (req.headers["x-request-id"] || "").trim() || randomUUID();

  res.setHeader("Access-Control-Allow-Origin",   "*");
  res.setHeader("Access-Control-Allow-Methods",  "POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers",  "Content-Type, X-API-Key, X-Request-ID");
  res.setHeader("Access-Control-Expose-Headers", "X-Request-ID, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset");
  res.setHeader("X-Request-ID", requestId);

  if (req.method === "OPTIONS") return res.status(204).end();

  if (req.method !== "POST") {
    return res.status(405).json({
      success: false,
      error: {
        code:    "METHOD_NOT_ALLOWED",
        message: "This endpoint only accepts POST requests.",
      },
    });
  }

  // ── API key validation ────────────────────────────────────────────────────
  const configuredKeys = (process.env.PARAGON_API_KEYS ?? "")
    .split(",")
    .map((k) => k.trim())
    .filter(Boolean);
  const providedKey = String(req.headers["x-api-key"] ?? "").trim();
  const isKeyHolder  = configuredKeys.length > 0 && configuredKeys.includes(providedKey);

  // ── Rate limiting ─────────────────────────────────────────────────────────
  const ip = (req.headers["x-forwarded-for"] ?? "")
    .split(",")[0]
    .trim() || req.socket?.remoteAddress || "unknown";

  const rateLimit = isKeyHolder ? 300 : 60;
  const rate = checkRate(ip, rateLimit);

  res.setHeader("X-RateLimit-Limit",     rate.limit);
  res.setHeader("X-RateLimit-Remaining", rate.remaining);
  res.setHeader("X-RateLimit-Reset",     rate.resetIn);

  if (!rate.allowed) {
    res.setHeader("Retry-After", rate.resetIn);
    return res.status(429).json({
      success: false,
      error: {
        code:        "RATE_LIMITED",
        message:     `Rate limit exceeded. Try again in ${rate.resetIn}s.`,
        retry_after: rate.resetIn,
      },
      rate_limit: {
        limit:            rate.limit,
        remaining:        0,
        reset_in_seconds: rate.resetIn,
        window:           "60s",
      },
    });
  }

  // ── Parse body ────────────────────────────────────────────────────────────
  const body = req.body ?? {};

  // tower — required
  const towerRaw = body.tower ?? body.paragon;
  if (towerRaw === undefined || towerRaw === null || String(towerRaw).trim() === "") {
    return res.status(400).json({
      success: false,
      error: {
        code:    "MISSING_FIELD",
        message: "Required field 'tower' is missing.",
        field:   "tower",
        hint:    "Pass a tower name (e.g. \"Dart Monkey\"), paragon name (e.g. \"Apex Plasma Master\"), or paragon ID (e.g. \"apex_plasma_master\").",
      },
    });
  }

  const paragon = findParagon(towerRaw);
  if (!paragon) {
    return res.status(400).json({
      success: false,
      error: {
        code:         "UNKNOWN_TOWER",
        message:      `Unknown tower "${towerRaw}". See valid_towers for accepted values.`,
        field:        "tower",
        valid_towers: Object.values(PARAGONS).map((p) => ({
          id:      p.id,
          tower:   p.tower,
          paragon: p.name,
        })),
      },
    });
  }

  // ── Validate and parse optional numeric / string fields ───────────────────

  const diffResult = validateDifficultyField(body.difficulty);
  if (diffResult.error) return res.status(400).json({ success: false, error: diffResult.error });
  const difficulty = diffResult.value;

  const playerCountResult = validateNumericField(
    body.player_count ?? body.playerCount,
    "player_count",
    { integer: true, min: 1, max: 4, defaultValue: 1 },
  );
  if (playerCountResult.error) return res.status(400).json({ success: false, error: playerCountResult.error });
  const playerCount = playerCountResult.value;

  const popsResult = validateNumericField(body.pops, "pops");
  if (popsResult.error) return res.status(400).json({ success: false, error: popsResult.error });
  const pops = popsResult.value;

  const incomeResult = validateNumericField(body.income, "income");
  if (incomeResult.error) return res.status(400).json({ success: false, error: incomeResult.error });
  const income = incomeResult.value;

  const cashSpentResult = validateNumericField(body.cash_spent ?? body.cashSpent, "cash_spent");
  if (cashSpentResult.error) return res.status(400).json({ success: false, error: cashSpentResult.error });
  const cashSpent = cashSpentResult.value;

  const sliderCashResult = validateNumericField(body.slider_cash ?? body.sliderCash, "slider_cash");
  if (sliderCashResult.error) return res.status(400).json({ success: false, error: sliderCashResult.error });
  const sliderCash = sliderCashResult.value;

  const tier5Result = validateNumericField(
    body.tier5_count ?? body.tier5Count,
    "tier5_count",
    { integer: true },
  );
  if (tier5Result.error) return res.status(400).json({ success: false, error: tier5Result.error });
  const tier5Count = tier5Result.value;

  const upgradeResult = validateNumericField(
    body.upgrade_count ?? body.upgradeCount,
    "upgrade_count",
    { integer: true },
  );
  if (upgradeResult.error) return res.status(400).json({ success: false, error: upgradeResult.error });
  const upgradeCount = upgradeResult.value;

  const totemsResult = validateNumericField(
    body.geraldo_totems ?? body.geraldoTotems,
    "geraldo_totems",
    { integer: true },
  );
  if (totemsResult.error) return res.status(400).json({ success: false, error: totemsResult.error });
  const totems = totemsResult.value;

  const gameMode = playerCount >= 2 ? "coop" : "solo";

  // ── Calculate ─────────────────────────────────────────────────────────────
  const calc = runCalculation({
    paragon,
    difficulty,
    gameMode,
    pops,
    income,
    upgrades:            upgradeCount,
    extraT5s:            tier5Count,
    sacrificedTowerCash: cashSpent,
    sliderCash,
    totems,
  });

  // ── Build response ────────────────────────────────────────────────────────
  return res.status(200).json({
    success:          true,
    api_version:      API_VERSION,
    formula_version:  FORMULA_VERSION,
    formula_revision: FORMULA_REVISION,
    formula: {
      game:  "BTD6",
      notes: [
        "Degree = calculateDegreeFromPower(totalPower) where totalPower = sum of all power sources.",
        "Power threshold for degrees 2-99: floor((50D³ + 5025D² + 168324D + 843000) / 600).",
        "Degree 1 = 0 power; Degree 100 = a flat 200,000 (the cubic only reaches 196,542 at D=100).",
        "Power caps: pops 90k | upgrades 10k | cash 60k | extra T5s 50k | totems uncapped.",
        "Extra T5s are clamped to what the mode allows: 9 in co-op, 0 solo (1 for Dart Monkey via Master Double Cross).",
      ],
    },
    result: {
      degree:                calc.degree,
      total_power:           calc.totalPower,
      power_for_next_degree: calc.powerForNext,
      next_degree:           calc.nextDegree,
      breakdown:             calc.breakdown,
      warnings:              calc.warnings,
      wasted_cash:           calc.wastedCash,
      paragon: {
        id:         paragon.id,
        name:       paragon.name,
        tower:      paragon.tower,
        base_price: calc.basePrice,
        difficulty,
        game_mode:  gameMode,
      },
    },
    rate_limit: {
      limit:            rate.limit,
      remaining:        rate.remaining,
      reset_in_seconds: rate.resetIn,
      window:           "60s",
    },
  });
}
