/**
 * POST /api/paragon/calculate
 * BTD6 Paragon degree calculator — designed for Discord bots and external integrations.
 *
 * ── Required body field ───────────────────────────────────────────────────────
 *   tower          {string}  Tower name, paragon name, or paragon ID
 *                            e.g. "Dart Monkey", "Apex Plasma Master", "apex_plasma_master"
 *
 * ── Optional body fields (all default to 0 / "medium" / 1) ───────────────────
 *   pops           {number}  Total pops across all sacrificed towers       (default: 0)
 *   cash_spent     {number}  Cash spent on non-T5 towers before sacrifice  (default: 0)
 *   tier5_count    {number}  Extra T5s sacrificed BEYOND the 3 required    (default: 0, integer)
 *   upgrade_count  {number}  Total upgrade tiers on sacrificed non-T5s     (default: 0, integer)
 *   geraldo_totems {number}  Geraldo Paragon Power Totems absorbed          (default: 0, integer)
 *   player_count   {number}  1 = solo, 2–4 = co-op                         (default: 1, integer 1–4)
 *   difficulty     {string}  "easy"|"medium"|"hard"|"impoppable"            (default: "medium")
 *   income         {number}  Cash income generated by sacrificed towers     (default: 0)
 *   slider_cash    {number}  Cash injected via the in-game cash slider      (default: 0)
 *
 * ── Auth (optional) ───────────────────────────────────────────────────────────
 *   Send X-API-Key header.  Set PARAGON_API_KEYS env var (comma-separated list)
 *   to enable.  Valid key holders get 300 req/min instead of 60 req/min.
 *   Leave PARAGON_API_KEYS unset to run without key enforcement.
 *
 * ── Rate limit headers ────────────────────────────────────────────────────────
 *   X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset
 *   Retry-After (on 429 responses only)
 *
 * ── Request / Response tracing ───────────────────────────────────────────────
 *   X-Request-ID is echoed on every response (generated if not supplied by client).
 *
 * ── Note on rate-limit reliability ───────────────────────────────────────────
 *   This endpoint is a Vercel serverless function; each cold-start instance has
 *   its own in-memory counter.  Counts are best-effort.  Use the response headers
 *   to self-throttle on the client side.
 */

import { randomUUID } from "node:crypto";
import {
  API_VERSION, FORMULA_VERSION, FORMULA_REVISION,
  VALID_DIFFICULTIES, PARAGONS, POWER_LIMITS,
} from "../_lib/shared.js";

// ─── Calculator ──────────────────────────────────────────────────────────────

function getBasePrice(mediumCost, difficulty) {
  const mult = { easy: 0.85, medium: 1.0, hard: 1.08, impoppable: 1.20 }[difficulty] ?? 1.0;
  return Math.round((mediumCost * mult) / 5) * 5;
}

function getPowerThreshold(degree) {
  if (degree <= 1) return 0;
  if (degree >= 100) return 200000;
  return Math.floor(
    (50 * degree ** 3 + 5025 * degree ** 2 + 168324 * degree + 843000) / 600
  );
}

function calculateDegreeFromPower(power) {
  if (power >= 200000) return 100;
  if (power <= 0) return 1;
  for (let d = 99; d >= 1; d--) {
    if (power >= getPowerThreshold(d)) return d;
  }
  return 1;
}

function runCalculation({
  paragon, difficulty, gameMode,
  pops, income, upgrades, extraT5s,
  sacrificedTowerCash, sliderCash, totems,
}) {
  const basePrice = getBasePrice(paragon.mediumCost, difficulty);

  // Extra T5s (solo: only Dart Monkey can have 1 extra via Master Double Cross)
  const effectiveExtraT5s =
    gameMode === "coop"
      ? extraT5s
      : paragon.id === "apex_plasma_master"
        ? Math.min(extraT5s, 1)
        : 0;

  const rawT5Power      = effectiveExtraT5s * POWER_LIMITS.t5.pointsPerExtra;
  const t5Power         = Math.min(POWER_LIMITS.t5.maxPower, rawT5Power);

  const rawUpgradesPow  = upgrades * POWER_LIMITS.upgrades.pointsPerUpgrade;
  const upgradesPower   = Math.min(POWER_LIMITS.upgrades.maxPower, rawUpgradesPow);

  const equivalentPops  = pops + income * 4;
  const rawPopsPower    = Math.floor(equivalentPops / POWER_LIMITS.pops.popDivisor);
  const popsPower       = Math.min(POWER_LIMITS.pops.maxPower, rawPopsPower);

  const sacrificePowerRatio = 20000 / basePrice;
  const sliderPowerRatio    = 20000 / (basePrice * 1.05);
  const rawSacrificePow     = sacrificedTowerCash * sacrificePowerRatio;
  const rawSliderPow        = sliderCash * sliderPowerRatio;
  const rawCashPower        = rawSacrificePow + rawSliderPow;
  const cashPower           = Math.floor(Math.min(POWER_LIMITS.cash.maxPower, rawCashPower));
  const cashCapped          = rawCashPower > POWER_LIMITS.cash.maxPower;

  let wastedCash = 0;
  if (cashCapped) {
    if (rawSacrificePow >= POWER_LIMITS.cash.maxPower) {
      wastedCash =
        sacrificedTowerCash - POWER_LIMITS.cash.maxPower / sacrificePowerRatio
        + sliderCash;
    } else {
      wastedCash =
        sliderCash - (POWER_LIMITS.cash.maxPower - rawSacrificePow) / sliderPowerRatio;
    }
    wastedCash = Math.max(0, Math.round(wastedCash));
  }

  const totemsPower = totems * 2000;

  const totalPower   = t5Power + upgradesPower + popsPower + cashPower + totemsPower;
  const degree       = calculateDegreeFromPower(totalPower);
  const nextDegree   = Math.min(100, degree + 1);
  const powerForNext = nextDegree === degree ? 0 : getPowerThreshold(nextDegree) - totalPower;

  const warnings = [];

  if (extraT5s > 0 && gameMode === "solo" && paragon.id !== "apex_plasma_master") {
    warnings.push({
      type: "invalid_extra_t5s_solo",
      message:
        "In solo play, only Dart Monkey can sacrifice an extra T5 (via Master Double Cross). " +
        "Extra T5s were ignored for this calculation.",
    });
  }
  if (rawT5Power > POWER_LIMITS.t5.maxPower) {
    const wasted = Math.floor((rawT5Power - POWER_LIMITS.t5.maxPower) / POWER_LIMITS.t5.pointsPerExtra);
    warnings.push({
      type: "extra_t5s_capped",
      message: `Extra-T5 power is capped at 50,000. ${wasted} extra T5(s) provide no benefit.`,
    });
  }
  if (rawUpgradesPow > POWER_LIMITS.upgrades.maxPower) {
    warnings.push({
      type: "upgrades_capped",
      message: `Upgrade power is capped at 10,000. ${upgrades - 100} upgrade tier(s) are wasted.`,
    });
  }
  if (rawPopsPower > POWER_LIMITS.pops.maxPower) {
    const wastedPops = Math.round(equivalentPops - 16200000);
    warnings.push({
      type: "pops_capped",
      message: `Pops/income power is capped at 90,000. ${wastedPops.toLocaleString()} equivalent pop(s) are wasted.`,
    });
  }
  if (cashCapped && wastedCash > 0) {
    warnings.push({
      type: "cash_capped",
      message: `Cash power is capped at 60,000. $${wastedCash.toLocaleString()} is wasted — reduce cash sacrifice or slider input.`,
    });
  }

  return {
    basePrice, totalPower, degree, nextDegree, powerForNext,
    breakdown: {
      pops: {
        power:     popsPower,
        max_power: POWER_LIMITS.pops.maxPower,
        capped:    rawPopsPower > POWER_LIMITS.pops.maxPower,
        fill_pct:  round2(popsPower / POWER_LIMITS.pops.maxPower * 100),
        note:      "1 power per 180 pops (equivalent: $45 income = 180 pops)",
      },
      upgrades: {
        power:     upgradesPower,
        max_power: POWER_LIMITS.upgrades.maxPower,
        capped:    rawUpgradesPow > POWER_LIMITS.upgrades.maxPower,
        fill_pct:  round2(upgradesPower / POWER_LIMITS.upgrades.maxPower * 100),
        note:      "100 power per upgrade tier on sacrificed non-T5 towers (max 100 tiers = 10,000 power)",
      },
      cash: {
        power:     cashPower,
        max_power: POWER_LIMITS.cash.maxPower,
        capped:    cashCapped,
        fill_pct:  round2(cashPower / POWER_LIMITS.cash.maxPower * 100),
        note:      `Power rate: ${round2(sacrificePowerRatio)} per $1 (sacrifice) / ${round2(sliderPowerRatio)} per $1 (slider, 5% premium)`,
      },
      extra_t5s: {
        power:     t5Power,
        max_power: POWER_LIMITS.t5.maxPower,
        capped:    rawT5Power > POWER_LIMITS.t5.maxPower,
        fill_pct:  round2(t5Power / POWER_LIMITS.t5.maxPower * 100),
        note:      "6,000 power per extra T5 beyond the 3 required to build the paragon (max ~8 extras = 50,000 power)",
      },
      totems: {
        power:     totemsPower,
        max_power: null,
        capped:    false,
        fill_pct:  null,
        note:      "2,000 power per Geraldo Paragon Power Totem (uncapped)",
      },
    },
    warnings,
    wastedCash,
  };
}

function round2(n) {
  return Math.round(n * 100) / 100;
}

// ─── Tower lookup ─────────────────────────────────────────────────────────────

function findParagon(input) {
  if (!input) return null;
  const q = String(input).trim().toLowerCase();
  return Object.values(PARAGONS).find(
    (p) =>
      p.id.toLowerCase() === q ||
      p.tower.toLowerCase() === q ||
      p.name.toLowerCase() === q
  ) ?? null;
}

// ─── Rate limiter (per-instance in-memory, best-effort) ──────────────────────

const rateMap = new Map();
const WINDOW_MS = 60_000;

function checkRate(ip, limit) {
  const now = Date.now();
  let entry = rateMap.get(ip);
  if (!entry || now >= entry.resetAt) {
    entry = { count: 0, resetAt: now + WINDOW_MS };
    rateMap.set(ip, entry);
  }
  entry.count++;
  return {
    allowed:   entry.count <= limit,
    remaining: Math.max(0, limit - entry.count),
    resetIn:   Math.ceil((entry.resetAt - now) / 1000),
    limit,
  };
}

const pruneTimer = setInterval(() => {
  const now = Date.now();
  for (const [k, v] of rateMap) {
    if (now >= v.resetAt) rateMap.delete(k);
  }
}, 5 * 60_000);
pruneTimer.unref?.();

// Exposed only for unit tests — not part of the public API surface.
export function _resetRateLimitForTesting() {
  rateMap.clear();
}

// ─── Input validation ─────────────────────────────────────────────────────────

const MAX_INPUT = 1e15; // guard against overflow abuse

/**
 * Validates a numeric field from the request body.
 * Returns { error, value } where error is null on success.
 * If val is absent/empty, returns the defaultValue without error.
 */
function validateNumericField(val, name, opts = {}) {
  const { integer = false, min = 0, max = MAX_INPUT, defaultValue = 0 } = opts;

  if (val === undefined || val === null || val === "") {
    return { error: null, value: defaultValue };
  }

  const n = Number(val);

  if (Number.isNaN(n)) {
    return {
      error: { code: "INVALID_FIELD", message: `'${name}' must be a number.`, field: name },
      value: null,
    };
  }
  if (!Number.isFinite(n)) {
    return {
      error: { code: "INVALID_FIELD", message: `'${name}' must be a finite number (not Infinity).`, field: name },
      value: null,
    };
  }
  if (n < min) {
    return {
      error: { code: "INVALID_FIELD", message: `'${name}' must be >= ${min}, got ${n}.`, field: name },
      value: null,
    };
  }
  if (n > max) {
    return {
      error: { code: "INVALID_FIELD", message: `'${name}' must be <= ${max}, got ${n}.`, field: name },
      value: null,
    };
  }
  if (integer && !Number.isInteger(n)) {
    return {
      error: { code: "INVALID_FIELD", message: `'${name}' must be a whole number (no decimals), got ${n}.`, field: name },
      value: null,
    };
  }

  return { error: null, value: n };
}

function validateDifficultyField(val) {
  if (val === undefined || val === null || val === "") {
    return { error: null, value: "medium" };
  }
  const v = String(val).toLowerCase().trim();
  if (!VALID_DIFFICULTIES.includes(v)) {
    return {
      error: {
        code:               "INVALID_FIELD",
        message:            `'difficulty' must be one of: ${VALID_DIFFICULTIES.join(", ")}. Got "${val}".`,
        field:              "difficulty",
        valid_difficulties: VALID_DIFFICULTIES,
      },
      value: null,
    };
  }
  return { error: null, value: v };
}

// ─── Handler ──────────────────────────────────────────────────────────────────

export default function handler(req, res) {
  // Echo or generate a request-scoped tracing ID.
  const requestId = (req.headers["x-request-id"] || "").trim() || randomUUID();

  res.setHeader("Access-Control-Allow-Origin",   "*");
  res.setHeader("Access-Control-Allow-Methods",  "POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers",  "Content-Type, X-API-Key, X-Request-ID");
  res.setHeader("Access-Control-Expose-Headers", "X-Request-ID, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset");
  res.setHeader("X-Request-ID", requestId);

  if (req.method === "OPTIONS") return res.status(204).end();

  if (req.method !== "POST") {
    return res.status(405).json({
      success: false,
      error: {
        code:    "METHOD_NOT_ALLOWED",
        message: "This endpoint only accepts POST requests.",
      },
    });
  }

  // ── API key validation ────────────────────────────────────────────────────
  const configuredKeys = (process.env.PARAGON_API_KEYS ?? "")
    .split(",")
    .map((k) => k.trim())
    .filter(Boolean);
  const providedKey = String(req.headers["x-api-key"] ?? "").trim();
  const isKeyHolder  = configuredKeys.length > 0 && configuredKeys.includes(providedKey);

  // ── Rate limiting ─────────────────────────────────────────────────────────
  const ip = (req.headers["x-forwarded-for"] ?? "")
    .split(",")[0]
    .trim() || req.socket?.remoteAddress || "unknown";

  const rateLimit = isKeyHolder ? 300 : 60;
  const rate = checkRate(ip, rateLimit);

  res.setHeader("X-RateLimit-Limit",     rate.limit);
  res.setHeader("X-RateLimit-Remaining", rate.remaining);
  res.setHeader("X-RateLimit-Reset",     rate.resetIn);

  if (!rate.allowed) {
    res.setHeader("Retry-After", rate.resetIn);
    return res.status(429).json({
      success: false,
      error: {
        code:        "RATE_LIMITED",
        message:     `Rate limit exceeded. Try again in ${rate.resetIn}s.`,
        retry_after: rate.resetIn,
      },
      rate_limit: {
        limit:            rate.limit,
        remaining:        0,
        reset_in_seconds: rate.resetIn,
        window:           "60s",
      },
    });
  }

  // ── Parse body ────────────────────────────────────────────────────────────
  const body = req.body ?? {};

  // tower — required
  const towerRaw = body.tower ?? body.paragon;
  if (towerRaw === undefined || towerRaw === null || String(towerRaw).trim() === "") {
    return res.status(400).json({
      success: false,
      error: {
        code:    "MISSING_FIELD",
        message: "Required field 'tower' is missing.",
        field:   "tower",
        hint:    "Pass a tower name (e.g. \"Dart Monkey\"), paragon name (e.g. \"Apex Plasma Master\"), or paragon ID (e.g. \"apex_plasma_master\").",
      },
    });
  }

  const paragon = findParagon(towerRaw);
  if (!paragon) {
    return res.status(400).json({
      success: false,
      error: {
        code:         "UNKNOWN_TOWER",
        message:      `Unknown tower "${towerRaw}". See valid_towers for accepted values.`,
        field:        "tower",
        valid_towers: Object.values(PARAGONS).map((p) => ({
          id:      p.id,
          tower:   p.tower,
          paragon: p.name,
        })),
      },
    });
  }

  // ── Validate and parse optional numeric / string fields ───────────────────

  const diffResult = validateDifficultyField(body.difficulty);
  if (diffResult.error) return res.status(400).json({ success: false, error: diffResult.error });
  const difficulty = diffResult.value;

  const playerCountResult = validateNumericField(
    body.player_count ?? body.playerCount,
    "player_count",
    { integer: true, min: 1, max: 4, defaultValue: 1 },
  );
  if (playerCountResult.error) return res.status(400).json({ success: false, error: playerCountResult.error });
  const playerCount = playerCountResult.value;

  const popsResult = validateNumericField(body.pops, "pops");
  if (popsResult.error) return res.status(400).json({ success: false, error: popsResult.error });
  const pops = popsResult.value;

  const incomeResult = validateNumericField(body.income, "income");
  if (incomeResult.error) return res.status(400).json({ success: false, error: incomeResult.error });
  const income = incomeResult.value;

  const cashSpentResult = validateNumericField(body.cash_spent ?? body.cashSpent, "cash_spent");
  if (cashSpentResult.error) return res.status(400).json({ success: false, error: cashSpentResult.error });
  const cashSpent = cashSpentResult.value;

  const sliderCashResult = validateNumericField(body.slider_cash ?? body.sliderCash, "slider_cash");
  if (sliderCashResult.error) return res.status(400).json({ success: false, error: sliderCashResult.error });
  const sliderCash = sliderCashResult.value;

  const tier5Result = validateNumericField(
    body.tier5_count ?? body.tier5Count,
    "tier5_count",
    { integer: true },
  );
  if (tier5Result.error) return res.status(400).json({ success: false, error: tier5Result.error });
  const tier5Count = tier5Result.value;

  const upgradeResult = validateNumericField(
    body.upgrade_count ?? body.upgradeCount,
    "upgrade_count",
    { integer: true },
  );
  if (upgradeResult.error) return res.status(400).json({ success: false, error: upgradeResult.error });
  const upgradeCount = upgradeResult.value;

  const totemsResult = validateNumericField(
    body.geraldo_totems ?? body.geraldoTotems,
    "geraldo_totems",
    { integer: true },
  );
  if (totemsResult.error) return res.status(400).json({ success: false, error: totemsResult.error });
  const totems = totemsResult.value;

  const gameMode = playerCount >= 2 ? "coop" : "solo";

  // ── Calculate ─────────────────────────────────────────────────────────────
  const calc = runCalculation({
    paragon,
    difficulty,
    gameMode,
    pops,
    income,
    upgrades:            upgradeCount,
    extraT5s:            tier5Count,
    sacrificedTowerCash: cashSpent,
    sliderCash,
    totems,
  });

  // ── Build response ────────────────────────────────────────────────────────
  return res.status(200).json({
    success:          true,
    api_version:      API_VERSION,
    formula_version:  FORMULA_VERSION,
    formula_revision: FORMULA_REVISION,
    formula: {
      game:  "BTD6",
      notes: [
        "Degree = calculateDegreeFromPower(totalPower) where totalPower = sum of all power sources.",
        "Power threshold per degree D: floor((50D³ + 5025D² + 168324D + 843000) / 600).",
        "Maximum: 200,000 total power = Degree 100.",
        "Power caps: pops 90k | upgrades 10k | cash 60k | extra T5s 50k | totems uncapped.",
      ],
    },
    result: {
      degree:                calc.degree,
      total_power:           calc.totalPower,
      power_for_next_degree: calc.powerForNext,
      next_degree:           calc.nextDegree,
      breakdown:             calc.breakdown,
      warnings:              calc.warnings,
      wasted_cash:           calc.wastedCash,
      paragon: {
        id:         paragon.id,
        name:       paragon.name,
        tower:      paragon.tower,
        base_price: calc.basePrice,
        difficulty,
        game_mode:  gameMode,
      },
    },
    rate_limit: {
      limit:            rate.limit,
      remaining:        rate.remaining,
      reset_in_seconds: rate.resetIn,
      window:           "60s",
    },
  });
}
