/**
 * POST /api/paragon/calculate
 * BTD6 Paragon degree calculator — designed for Discord bots and external integrations.
 *
 * ── Required body field ───────────────────────────────────────────────────────
 *   tower          {string}  Tower name, paragon name, or paragon ID
 *                            e.g. "Dart Monkey", "Apex Plasma Master", "apex_plasma_master"
 *
 * ── Optional body fields (all default to 0 / "medium" / 1) ───────────────────
 *   pops           {number}  Total pops across all sacrificed towers       (default: 0)
 *   cash_spent     {number}  Cash spent on non-T5 towers before sacrifice  (default: 0)
 *   tier5_count    {number}  Extra T5s sacrificed BEYOND the 3 required    (default: 0)
 *   upgrade_count  {number}  Total upgrade tiers on sacrificed non-T5s     (default: 0)
 *   geraldo_totems {number}  Geraldo Paragon Power Totems absorbed          (default: 0)
 *   player_count   {number}  1 = solo, 2–4 = co-op                         (default: 1)
 *   difficulty     {string}  "easy"|"medium"|"hard"|"impoppable"            (default: "medium")
 *   income         {number}  Cash income generated by sacrificed towers     (default: 0)
 *   slider_cash    {number}  Cash injected via the in-game cash slider      (default: 0)
 *
 * ── Auth (optional) ───────────────────────────────────────────────────────────
 *   Send X-API-Key header.  Set PARAGON_API_KEYS env var (comma-separated list)
 *   to enable.  Valid key holders get 300 req/min instead of 60 req/min.
 *   Leave PARAGON_API_KEYS unset to run without key enforcement.
 *
 * ── Rate limit headers ────────────────────────────────────────────────────────
 *   X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset
 *
 * ── Note on rate-limit reliability ───────────────────────────────────────────
 *   This endpoint is a Vercel serverless function; each cold-start instance has
 *   its own in-memory counter.  Counts are best-effort.  Use the response headers
 *   to self-throttle on the client side.
 */

// ─── Paragon data (mirrors src/constants/paragons.js) ────────────────────────

const PARAGONS = {
  apex_plasma_master: {
    id: "apex_plasma_master", name: "Apex Plasma Master",
    tower: "Dart Monkey", mediumCost: 150000,
  },
  glaive_dominus: {
    id: "glaive_dominus", name: "Glaive Dominus",
    tower: "Boomerang Monkey", mediumCost: 375000,
  },
  ascended_shadow: {
    id: "ascended_shadow", name: "Ascended Shadow",
    tower: "Ninja Monkey", mediumCost: 500000,
  },
  navarch_of_the_seas: {
    id: "navarch_of_the_seas", name: "Navarch of the Seas",
    tower: "Monkey Buccaneer", mediumCost: 500000,
  },
  nautic_siege_core: {
    id: "nautic_siege_core", name: "Nautic Siege Core",
    tower: "Monkey Sub", mediumCost: 400000,
  },
  master_builder: {
    id: "master_builder", name: "Master Builder",
    tower: "Engineer Monkey", mediumCost: 650000,
  },
  magus_perfectus: {
    id: "magus_perfectus", name: "Magus Perfectus",
    tower: "Wizard Monkey", mediumCost: 800000,
  },
  goliath_doomship: {
    id: "goliath_doomship", name: "Goliath Doomship",
    tower: "Monkey Ace", mediumCost: 900000,
  },
  crucible_of_steel_and_flame: {
    id: "crucible_of_steel_and_flame", name: "Crucible of Steel and Flame",
    tower: "Tack Shooter", mediumCost: 200000,
  },
  mega_massive_munitions_factory: {
    id: "mega_massive_munitions_factory", name: "Mega Massive Munitions Factory",
    tower: "Spike Factory", mediumCost: 750000,
  },
  ballistic_obliteration_missile_bunker: {
    id: "ballistic_obliteration_missile_bunker",
    name: "Ballistic Obliteration Missile Bunker (B.O.M.B.)",
    tower: "Bomb Shooter", mediumCost: 600000,
  },
  herald_of_everfrost: {
    id: "herald_of_everfrost", name: "Herald of Everfrost",
    tower: "Ice Monkey", mediumCost: 300000,
  },
  root_of_all_nature: {
    id: "root_of_all_nature", name: "Root of all Nature",
    tower: "Druid", mediumCost: 475000,
  },
};

const POWER_LIMITS = {
  t5:       { maxPower: 50000, pointsPerExtra: 6000 },
  upgrades: { maxPower: 10000, pointsPerUpgrade: 100 },
  pops:     { maxPower: 90000, popDivisor: 180 },
  cash:     { maxPower: 60000 },
};

// ─── Calculator (mirrors src/utils/calculator.js) ────────────────────────────

function getBasePrice(mediumCost, difficulty) {
  const mult = { easy: 0.85, medium: 1.0, hard: 1.08, impoppable: 1.20 }[difficulty] ?? 1.0;
  return Math.round((mediumCost * mult) / 5) * 5;
}

function getPowerThreshold(degree) {
  if (degree <= 1) return 0;
  if (degree >= 100) return 200000;
  return Math.floor(
    (50 * degree ** 3 + 5025 * degree ** 2 + 168324 * degree + 843000) / 600
  );
}

function calculateDegreeFromPower(power) {
  if (power >= 200000) return 100;
  if (power <= 0) return 1;
  for (let d = 99; d >= 1; d--) {
    if (power >= getPowerThreshold(d)) return d;
  }
  return 1;
}

function runCalculation({
  paragon, difficulty, gameMode,
  pops, income, upgrades, extraT5s,
  sacrificedTowerCash, sliderCash, totems,
}) {
  const basePrice = getBasePrice(paragon.mediumCost, difficulty);

  // Extra T5s (solo: only Dart Monkey can have 1 extra via Master Double Cross)
  const effectiveExtraT5s =
    gameMode === "coop"
      ? extraT5s
      : paragon.id === "apex_plasma_master"
        ? Math.min(extraT5s, 1)
        : 0;

  const rawT5Power      = effectiveExtraT5s * POWER_LIMITS.t5.pointsPerExtra;
  const t5Power         = Math.min(POWER_LIMITS.t5.maxPower, rawT5Power);

  const rawUpgradesPow  = upgrades * POWER_LIMITS.upgrades.pointsPerUpgrade;
  const upgradesPower   = Math.min(POWER_LIMITS.upgrades.maxPower, rawUpgradesPow);

  const equivalentPops  = pops + income * 4;
  const rawPopsPower    = Math.floor(equivalentPops / POWER_LIMITS.pops.popDivisor);
  const popsPower       = Math.min(POWER_LIMITS.pops.maxPower, rawPopsPower);

  const sacrificePowerRatio = 20000 / basePrice;
  const sliderPowerRatio    = 20000 / (basePrice * 1.05);
  const rawSacrificePow     = sacrificedTowerCash * sacrificePowerRatio;
  const rawSliderPow        = sliderCash * sliderPowerRatio;
  const rawCashPower        = rawSacrificePow + rawSliderPow;
  const cashPower           = Math.floor(Math.min(POWER_LIMITS.cash.maxPower, rawCashPower));
  const cashCapped          = rawCashPower > POWER_LIMITS.cash.maxPower;

  let wastedCash = 0;
  if (cashCapped) {
    if (rawSacrificePow >= POWER_LIMITS.cash.maxPower) {
      wastedCash =
        sacrificedTowerCash - POWER_LIMITS.cash.maxPower / sacrificePowerRatio
        + sliderCash;
    } else {
      wastedCash =
        sliderCash - (POWER_LIMITS.cash.maxPower - rawSacrificePow) / sliderPowerRatio;
    }
    wastedCash = Math.max(0, Math.round(wastedCash));
  }

  const totemsPower = totems * 2000;

  const totalPower        = t5Power + upgradesPower + popsPower + cashPower + totemsPower;
  const degree            = calculateDegreeFromPower(totalPower);
  const nextDegree        = Math.min(100, degree + 1);
  const powerForNext      = nextDegree === degree ? 0 : getPowerThreshold(nextDegree) - totalPower;

  // ── Warnings ──────────────────────────────────────────────────────────────
  const warnings = [];

  if (extraT5s > 0 && gameMode === "solo" && paragon.id !== "apex_plasma_master") {
    warnings.push({
      type: "invalid_extra_t5s_solo",
      message:
        "In solo play, only Dart Monkey can sacrifice an extra T5 (via Master Double Cross). " +
        "Extra T5s were ignored for this calculation.",
    });
  }
  if (rawT5Power > POWER_LIMITS.t5.maxPower) {
    const wasted = Math.floor((rawT5Power - POWER_LIMITS.t5.maxPower) / POWER_LIMITS.t5.pointsPerExtra);
    warnings.push({
      type: "extra_t5s_capped",
      message: `Extra-T5 power is capped at 50,000. ${wasted} extra T5(s) provide no benefit.`,
    });
  }
  if (rawUpgradesPow > POWER_LIMITS.upgrades.maxPower) {
    warnings.push({
      type: "upgrades_capped",
      message: `Upgrade power is capped at 10,000. ${upgrades - 100} upgrade tier(s) are wasted.`,
    });
  }
  if (rawPopsPower > POWER_LIMITS.pops.maxPower) {
    const wastedPops = Math.round(equivalentPops - 16200000);
    warnings.push({
      type: "pops_capped",
      message: `Pops/income power is capped at 90,000. ${wastedPops.toLocaleString()} equivalent pop(s) are wasted.`,
    });
  }
  if (cashCapped && wastedCash > 0) {
    warnings.push({
      type: "cash_capped",
      message: `Cash power is capped at 60,000. $${wastedCash.toLocaleString()} is wasted — reduce cash sacrifice or slider input.`,
    });
  }

  return {
    basePrice,
    totalPower,
    degree,
    nextDegree,
    powerForNext,
    breakdown: {
      pops: {
        power:      popsPower,
        max_power:  POWER_LIMITS.pops.maxPower,
        capped:     rawPopsPower > POWER_LIMITS.pops.maxPower,
        fill_pct:   round2(popsPower / POWER_LIMITS.pops.maxPower * 100),
        note:       "1 power per 180 pops (equivalent: $45 income = 180 pops)",
      },
      upgrades: {
        power:      upgradesPower,
        max_power:  POWER_LIMITS.upgrades.maxPower,
        capped:     rawUpgradesPow > POWER_LIMITS.upgrades.maxPower,
        fill_pct:   round2(upgradesPower / POWER_LIMITS.upgrades.maxPower * 100),
        note:       "100 power per upgrade tier on sacrificed non-T5 towers (max 100 tiers = 10,000 power)",
      },
      cash: {
        power:      cashPower,
        max_power:  POWER_LIMITS.cash.maxPower,
        capped:     cashCapped,
        fill_pct:   round2(cashPower / POWER_LIMITS.cash.maxPower * 100),
        note:       `Power rate: ${round2(sacrificePowerRatio)} per $1 (sacrifice) / ${round2(sliderPowerRatio)} per $1 (slider, 5% premium)`,
      },
      extra_t5s: {
        power:      t5Power,
        max_power:  POWER_LIMITS.t5.maxPower,
        capped:     rawT5Power > POWER_LIMITS.t5.maxPower,
        fill_pct:   round2(t5Power / POWER_LIMITS.t5.maxPower * 100),
        note:       "6,000 power per extra T5 beyond the 3 required to build the paragon (max ~8 extras = 50,000 power)",
      },
      totems: {
        power:      totemsPower,
        max_power:  null,
        capped:     false,
        fill_pct:   null,
        note:       "2,000 power per Geraldo Paragon Power Totem (uncapped)",
      },
    },
    warnings,
    wastedCash,
  };
}

function round2(n) {
  return Math.round(n * 100) / 100;
}

// ─── Tower lookup ─────────────────────────────────────────────────────────────

function findParagon(input) {
  if (!input) return null;
  const q = String(input).trim().toLowerCase();
  return Object.values(PARAGONS).find(
    (p) =>
      p.id.toLowerCase() === q ||
      p.tower.toLowerCase() === q ||
      p.name.toLowerCase() === q
  ) ?? null;
}

// ─── Rate limiter (per-instance in-memory, best-effort) ──────────────────────

const rateMap = new Map();
const WINDOW_MS = 60_000;

function checkRate(ip, limit) {
  const now = Date.now();
  let entry = rateMap.get(ip);
  if (!entry || now >= entry.resetAt) {
    entry = { count: 0, resetAt: now + WINDOW_MS };
    rateMap.set(ip, entry);
  }
  entry.count++;
  return {
    allowed:    entry.count <= limit,
    remaining:  Math.max(0, limit - entry.count),
    resetIn:    Math.ceil((entry.resetAt - now) / 1000),
    limit,
  };
}

// Prevent stale entries from accumulating across warm instances
const pruneTimer = setInterval(() => {
  const now = Date.now();
  for (const [k, v] of rateMap) {
    if (now >= v.resetAt) rateMap.delete(k);
  }
}, 5 * 60_000);
pruneTimer.unref?.();

// ─── Input helpers ────────────────────────────────────────────────────────────

function parseNonNegNumber(val, fallback = 0) {
  const n = Number(val);
  return Number.isFinite(n) && n >= 0 ? n : fallback;
}

function parseNonNegInt(val, fallback = 0) {
  return Math.floor(parseNonNegNumber(val, fallback));
}

function parseDifficulty(val) {
  const v = String(val ?? "").toLowerCase().trim();
  return ["easy", "medium", "hard", "impoppable"].includes(v) ? v : "medium";
}

// ─── Handler ──────────────────────────────────────────────────────────────────

export default function handler(req, res) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type, X-API-Key");

  if (req.method === "OPTIONS") return res.status(204).end();

  if (req.method !== "POST") {
    return res.status(405).json({
      success: false,
      error: {
        code: "METHOD_NOT_ALLOWED",
        message: "This endpoint only accepts POST requests.",
      },
    });
  }

  // ── API key validation ────────────────────────────────────────────────────
  const configuredKeys = (process.env.PARAGON_API_KEYS ?? "")
    .split(",")
    .map((k) => k.trim())
    .filter(Boolean);
  const providedKey = String(req.headers["x-api-key"] ?? "").trim();
  const isKeyHolder  = configuredKeys.length > 0 && configuredKeys.includes(providedKey);

  // ── Rate limiting ─────────────────────────────────────────────────────────
  const ip = (req.headers["x-forwarded-for"] ?? "")
    .split(",")[0]
    .trim() || req.socket?.remoteAddress || "unknown";

  const rateLimit = isKeyHolder ? 300 : 60;
  const rate = checkRate(ip, rateLimit);

  res.setHeader("X-RateLimit-Limit",     rate.limit);
  res.setHeader("X-RateLimit-Remaining", rate.remaining);
  res.setHeader("X-RateLimit-Reset",     rate.resetIn);

  if (!rate.allowed) {
    return res.status(429).json({
      success: false,
      error: {
        code:        "RATE_LIMITED",
        message:     `Rate limit exceeded. Try again in ${rate.resetIn}s.`,
        retry_after: rate.resetIn,
      },
      rate_limit: {
        limit:             rate.limit,
        remaining:         0,
        reset_in_seconds:  rate.resetIn,
        window:            "60s",
      },
    });
  }

  // ── Parse body ────────────────────────────────────────────────────────────
  const body = req.body ?? {};

  // tower — required
  const towerRaw = body.tower ?? body.paragon;
  if (towerRaw === undefined || towerRaw === null || String(towerRaw).trim() === "") {
    return res.status(400).json({
      success: false,
      error: {
        code:    "MISSING_FIELD",
        message: "Required field 'tower' is missing.",
        field:   "tower",
        hint:    "Pass a tower name (e.g. \"Dart Monkey\"), paragon name (e.g. \"Apex Plasma Master\"), or paragon ID (e.g. \"apex_plasma_master\").",
      },
    });
  }

  const paragon = findParagon(towerRaw);
  if (!paragon) {
    return res.status(400).json({
      success: false,
      error: {
        code:         "UNKNOWN_TOWER",
        message:      `Unknown tower "${towerRaw}". See valid_towers for accepted values.`,
        field:        "tower",
        valid_towers: Object.values(PARAGONS).map((p) => ({
          id:     p.id,
          tower:  p.tower,
          paragon: p.name,
        })),
      },
    });
  }

  // Numeric / optional fields
  const pops         = parseNonNegNumber(body.pops, 0);
  const income       = parseNonNegNumber(body.income, 0);
  const cashSpent    = parseNonNegNumber(body.cash_spent ?? body.cashSpent, 0);
  const sliderCash   = parseNonNegNumber(body.slider_cash ?? body.sliderCash, 0);
  const tier5Count   = parseNonNegInt(body.tier5_count ?? body.tier5Count, 0);
  const upgradeCount = parseNonNegInt(body.upgrade_count ?? body.upgradeCount, 0);
  const totems       = parseNonNegInt(body.geraldo_totems ?? body.geraldoTotems, 0);
  const playerCount  = Math.max(1, parseNonNegInt(body.player_count ?? body.playerCount, 1));
  const difficulty   = parseDifficulty(body.difficulty);
  const gameMode     = playerCount >= 2 ? "coop" : "solo";

  // ── Calculate ─────────────────────────────────────────────────────────────
  const calc = runCalculation({
    paragon,
    difficulty,
    gameMode,
    pops,
    income,
    upgrades:            upgradeCount,
    extraT5s:            tier5Count,
    sacrificedTowerCash: cashSpent,
    sliderCash,
    totems,
  });

  // ── Build response ────────────────────────────────────────────────────────
  return res.status(200).json({
    success:     true,
    api_version: "1.0",
    formula: {
      game:  "BTD6",
      notes: [
        "Degree = calculateDegreeFromPower(totalPower) where totalPower = sum of all power sources.",
        "Power threshold per degree D: floor((50D³ + 5025D² + 168324D + 843000) / 600).",
        "Maximum: 200,000 total power = Degree 100.",
        "Power caps: pops 90k | upgrades 10k | cash 60k | extra T5s 50k | totems uncapped.",
      ],
    },
    result: {
      degree:               calc.degree,
      total_power:          calc.totalPower,
      power_for_next_degree: calc.powerForNext,
      next_degree:          calc.nextDegree,
      breakdown:            calc.breakdown,
      warnings:             calc.warnings,
      wasted_cash:          calc.wastedCash,
      paragon: {
        id:         paragon.id,
        name:       paragon.name,
        tower:      paragon.tower,
        base_price: calc.basePrice,
        difficulty,
        game_mode:  gameMode,
      },
    },
    rate_limit: {
      limit:            rate.limit,
      remaining:        rate.remaining,
      reset_in_seconds: rate.resetIn,
      window:           "60s",
    },
  });
}
